apiVersion: batch/v1
kind: Job
metadata:
  name: job-fine-test
spec:
  parallelism: 2
  template:
    metadata:
      name: job-fine-test
      labels:
        jobgroup: fine-example
    spec:
      containers:
      - name: c
        image: mtoto/job-fine-test
      restartPolicy: OnFailure
