apiVersion: batch/v1
kind: Job
metadata:
  name: static-demo
spec:
  parallelism: 20
  completions: 100
  template:
    metadata:
      name: static-example
      labels:
        jobgroup: static-example
    spec:
      containers:
      - name: birthday
        image: mtoto/mc-demo
        command: ["Rscript", "monte-carlo.R"]
      restartPolicy: Never
      
